### ISSUE TITLE
Problem parsing some keys

### ISSUE THREAD

**Issue by grennis** [campagnola/pyabc#7]
Hi, there seems to be a bug parsing some keys. For example, key of Db major. This line of code:

https://github.com/campagnola/pyabc/blob/master/pyabc.py#L152

Will convert keys to ionian, but also has the side effect of changing the key from Db to C# (as if it were a pitch). So the accidentals are applied from key C# instead of Db.

**Comment by campagnola** [comment]
Fixed, but now I'm curious why you closed the issue?

**Comment by grennis** [comment]
I thought I did not do a good job describing the bug. I was going to re-open a new one with a better description and specific reproduce case, but you have already fixed it. The fix looks good, thanks!
