### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by olets** [campagnola/pyabc#8]
If I understand correctly, one of the things pyabc tries to do is determine an abc tune's key from the notes. Is that right? How do I do that?

I've only tried `pyabc` (thinking that might run it on your `tunes` test array) and `pyabc /path/to/my/tune.abc`

Thanks!

**Comment by campagnola** [comment]
Sorry @olets, that feature is still on the wishlist :)
For now it's just an ABC parser.
